name: virtual_phone
version: 1.0.0
description: A web-based smart phone simulator.
homepage: https://github.com/rubydogjp/packages/tree/main/virtual_phone
publish_to: none

environment:
  sdk: ^3.0.0
  flutter: ^3.16.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  freezed_annotation:
  json_annotation:
  collection:
  flutter_riverpod:
  flutter_hooks:
  uuid:

dev_dependencies:
  flutter_lints:
  build_runner:
  freezed:
  json_serializable:

flutter:
  assets:
    - assets/images/
    - assets/fonts/OFL.txt
  fonts:
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/NotoSansJP-Bold.otf
        - asset: assets/fonts/NotoSansJP-Regular.otf
